-- Podio Clone: Migration 39 - Phase 14: AI app builder install path.
-- ai_install_app(): installs a generated definition (app + fields + views +
-- simple automations with external_id field references), keeping a private
-- template row as provenance. (Applied via MCP; kept for fresh installs.)

create or replace function podio.ai_install_app(p_workspace uuid, p_definition jsonb)
returns jsonb
language plpgsql security definer set search_path = podio, public as $$
declare
  v_org uuid;
  v_tpl uuid;
  v_res jsonb;
  v_app uuid;
  v_auto jsonb;
  v_cond jsonb;
  v_conds jsonb;
  v_act jsonb;
  v_acts jsonb;
  v_fid uuid;
  v_n int := 0;
begin
  if not podio.is_workspace_member(p_workspace) then
    raise exception 'not a workspace member';
  end if;
  if p_definition->'app'->>'name' is null or jsonb_typeof(p_definition->'fields') <> 'array' then
    raise exception 'definition must contain app.name and a fields array';
  end if;
  select organization_id into v_org from podio.workspaces where id = p_workspace;

  insert into podio.app_templates
    (organization_id, name, description, category, definition, visibility, created_by)
  values (v_org, coalesce(p_definition->'app'->>'name','AI app') || ' (AI generated)',
    'Generated by the AI app builder', p_definition->>'category',
    p_definition, 'private', auth.uid())
  returning id into v_tpl;

  v_res := podio.install_app_template(v_tpl, p_workspace, false);
  v_app := (v_res->>'app_id')::uuid;

  for v_auto in select * from jsonb_array_elements(coalesce(p_definition->'automations','[]'::jsonb)) loop
    v_conds := '[]'::jsonb;
    for v_cond in select * from jsonb_array_elements(coalesce(v_auto->'conditions','[]'::jsonb)) loop
      select id into v_fid from podio.app_fields
      where app_id = v_app and external_id = v_cond->>'field_external_id' and status = 'active';
      if v_fid is not null then
        v_conds := v_conds || jsonb_build_array(
          (v_cond - 'field_external_id') || jsonb_build_object('field_id', v_fid));
      end if;
    end loop;

    v_acts := '[]'::jsonb;
    for v_act in select * from jsonb_array_elements(coalesce(v_auto->'actions','[]'::jsonb)) loop
      if v_act ? 'field_external_id' then
        select id into v_fid from podio.app_fields
        where app_id = v_app and external_id = v_act->>'field_external_id' and status = 'active';
        if v_fid is null then continue; end if;
        v_act := (v_act - 'field_external_id') || jsonb_build_object('field_id', v_fid);
      end if;
      v_acts := v_acts || jsonb_build_array(v_act);
    end loop;

    if jsonb_array_length(v_acts) > 0 then
      insert into podio.automations
        (workspace_id, app_id, name, kind, status, trigger, conditions, actions, created_by)
      values (p_workspace, v_app,
        coalesce(v_auto->>'name', 'AI automation'), 'simple', 'active',
        coalesce(v_auto->'trigger', '{"type":"item_created"}'::jsonb),
        v_conds, v_acts, auth.uid());
      v_n := v_n + 1;
    end if;
  end loop;

  return v_res || jsonb_build_object('automations_installed', v_n, 'template_id', v_tpl);
end $$;
grant execute on function podio.ai_install_app(uuid, jsonb) to authenticated;
