-- Podio Clone: Migration 37 - Phase 12c: scheduled flows, inbound-webhook trigger,
-- generate_pdf action, approval + loop steps, flow versioning, captcha flag, org backup.

-- ============================================================
-- 1) Scheduled flows
--    trigger config: { type:'scheduled', every:'hour'|'day'|'week', hour?, dow? }
--    hour = 0-23 UTC (default 9), dow = 0-6 Sunday-Saturday (default 1 Monday).
--    Runs over the app's items that pass the automation's conditions (50/run cap).
-- ============================================================
alter table podio.automations
  add column if not exists last_scheduled_at timestamptz;

create or replace function podio.process_scheduled_automations()
returns int
language plpgsql security definer set search_path = podio, public as $$
declare
  v_auto record;
  v_item record;
  v_every text;
  v_hour int;
  v_dow int;
  v_due boolean;
  v_count int := 0;
begin
  for v_auto in
    select * from podio.automations
    where status = 'active' and trigger->>'type' = 'scheduled' and app_id is not null
  loop
    v_every := coalesce(v_auto.trigger->>'every', 'day');
    v_hour := coalesce(nullif(v_auto.trigger->>'hour','')::int, 9);
    v_dow := coalesce(nullif(v_auto.trigger->>'dow','')::int, 1);

    v_due := case v_every
      when 'hour' then coalesce(v_auto.last_scheduled_at, '-infinity') <= now() - interval '55 minutes'
      when 'week' then extract(dow from now())::int = v_dow
        and extract(hour from now())::int >= v_hour
        and (v_auto.last_scheduled_at is null or v_auto.last_scheduled_at::date < current_date)
      else extract(hour from now())::int >= v_hour
        and (v_auto.last_scheduled_at is null or v_auto.last_scheduled_at::date < current_date)
    end;
    if not v_due then continue; end if;

    update podio.automations set last_scheduled_at = now() where id = v_auto.id;

    for v_item in
      select i.id from podio.items i
      where i.app_id = v_auto.app_id and not i.is_deleted
        and not exists (
          select 1 from jsonb_array_elements(v_auto.conditions) c
          where not podio.check_condition(i.id, c))
      order by i.created_at desc
      limit 50
    loop
      perform podio.execute_automation(v_auto.id, v_item.id,
        jsonb_build_object('type','scheduled','every', v_every),
        v_auto.created_by, false);
      v_count := v_count + 1;
    end loop;
  end loop;
  return v_count;
end $$;

do $$
begin
  perform cron.schedule('podio_process_scheduled_automations', '*/15 * * * *',
    'select podio.process_scheduled_automations()');
exception when others then null;
end $$;

-- ============================================================
-- 2) Inbound-webhook trigger
--    trigger config: { type:'webhook', token:'…' } (token generated by the builder)
--    POST /api/hooks/<automation_id>?token=… with { values: {external_id: value},
--    title? } to create an item and fire the flow, or { item_id } to fire on an
--    existing item.
-- ============================================================
create or replace function podio.trigger_inbound_webhook(
  p_automation uuid, p_token text, p_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql security definer set search_path = podio, public as $$
declare
  v_auto podio.automations;
  v_item podio.items;
  v_values jsonb;
  v_run uuid;
  v_created boolean := false;
begin
  select * into v_auto from podio.automations
  where id = p_automation and status = 'active' and trigger->>'type' = 'webhook';
  if v_auto.id is null then
    raise exception 'webhook automation not found or inactive';
  end if;
  if nullif(v_auto.trigger->>'token','') is null
     or v_auto.trigger->>'token' is distinct from p_token then
    raise exception 'invalid webhook token';
  end if;
  if v_auto.app_id is null then
    raise exception 'automation has no app';
  end if;

  if nullif(p_payload->>'item_id','') is not null then
    select * into v_item from podio.items
    where id = (p_payload->>'item_id')::uuid and app_id = v_auto.app_id and not is_deleted;
    if v_item.id is null then raise exception 'item not found in this app'; end if;
  else
    insert into podio.items (app_id, title, created_by)
    values (v_auto.app_id, nullif(p_payload->>'title',''), v_auto.created_by)
    returning * into v_item;
    v_created := true;

    select coalesce(jsonb_object_agg(af.id::text, p_payload->'values'->af.external_id), '{}'::jsonb)
      into v_values
    from podio.app_fields af
    where af.app_id = v_auto.app_id and af.status = 'active'
      and p_payload->'values' ? af.external_id;
    perform podio.write_values(v_auto.app_id, v_item.id, v_values, null);

    insert into podio.activity_events
      (organization_id, workspace_id, app_id, item_id, event_type, target_type, target_id, payload)
    select w.organization_id, a.workspace_id, a.id, v_item.id,
      'item_created', 'item', v_item.id,
      jsonb_build_object('via', 'inbound_webhook', 'automation', v_auto.name)
    from podio.apps a join podio.workspaces w on w.id = a.workspace_id
    where a.id = v_auto.app_id;
  end if;

  v_run := podio.execute_automation(v_auto.id, v_item.id,
    jsonb_build_object('type','webhook'), v_auto.created_by, false);

  return jsonb_build_object('item_id', v_item.id, 'item_created', v_created, 'run_id', v_run);
end $$;
grant execute on function podio.trigger_inbound_webhook(uuid, text, jsonb) to anon, authenticated;

-- ============================================================
-- 3) exec_action: add generate_pdf (posts a comment linking the item's PDF endpoint)
-- ============================================================
create or replace function podio.exec_action(
  p_action jsonb, p_org uuid, p_ws uuid, p_item uuid, p_actor uuid, p_auto_name text
)
returns jsonb
language plpgsql security definer set search_path = podio, public as $$
declare
  v_req bigint;
  v_url text;
  v_method text;
  v_cnt int;
  v_rel record;
begin
  case p_action->>'type'
    when 'create_task' then
      if p_actor is not null then
        insert into podio.tasks
          (organization_id, workspace_id, target_type, target_id, title, assignee_id, created_by, due_at)
        values
          (p_org, p_ws, 'item', p_item, p_action->>'title',
           nullif(p_action->>'assignee_id','')::uuid, p_actor,
           case when nullif(p_action->>'due_days','') is not null
             then now() + ((p_action->>'due_days')::int || ' days')::interval end);
        if nullif(p_action->>'assignee_id','') is not null
           and (p_action->>'assignee_id')::uuid <> p_actor then
          insert into podio.notifications (user_id, event_type, target_type, target_id, actor_id, payload)
          values ((p_action->>'assignee_id')::uuid, 'task_assigned', 'item', p_item, p_actor,
            jsonb_build_object('task_title', p_action->>'title', 'automation', p_auto_name));
        end if;
      end if;
    when 'update_field' then
      insert into podio.item_field_values (item_id, field_id, position, value, value_text, value_number)
      values (p_item, (p_action->>'field_id')::uuid, 0, p_action->'value',
        case when jsonb_typeof(p_action->'value') = 'string' then p_action->'value' #>> '{}' end,
        case when jsonb_typeof(p_action->'value') = 'number' then (p_action->'value' #>> '{}')::numeric end)
      on conflict (item_id, field_id, position) do update
        set value = excluded.value, value_text = excluded.value_text,
            value_number = excluded.value_number, updated_at = now();
    when 'notify' then
      if nullif(p_action->>'user_id','') is not null then
        insert into podio.notifications (user_id, event_type, target_type, target_id, actor_id, payload)
        values ((p_action->>'user_id')::uuid, 'automation', 'item', p_item, p_actor,
          jsonb_build_object('message', p_action->>'message', 'automation', p_auto_name));
      end if;
    when 'add_comment' then
      if p_actor is not null then
        insert into podio.comments (workspace_id, target_type, target_id, created_by, body)
        values (p_ws, 'item', p_item, p_actor, coalesce(p_action->>'body','(automation comment)'));
      end if;
    when 'send_email' then
      if nullif(p_action->>'to','') is not null then
        insert into podio.outbound_emails (organization_id, to_address, subject, body_text, item_id)
        values (p_org, p_action->>'to',
          coalesce(p_action->>'subject', 'Notification from ' || coalesce(p_auto_name,'automation')),
          p_action->>'body', p_item);
      end if;
    when 'http_request' then
      v_url := nullif(p_action->>'url','');
      if v_url is null or v_url !~* '^https?://' then
        return jsonb_build_object('action','http_request','ok',false,'reason','invalid url');
      end if;
      v_method := lower(coalesce(nullif(p_action->>'method',''), 'post'));
      if v_method = 'get' then
        select net.http_get(
          url := v_url,
          headers := coalesce(p_action->'headers','{}'::jsonb)
        ) into v_req;
      else
        select net.http_post(
          url := v_url,
          body := coalesce(p_action->'body',
            jsonb_build_object('item_id', p_item::text, 'automation', coalesce(p_auto_name,''))),
          headers := jsonb_build_object('Content-Type','application/json')
            || coalesce(p_action->'headers','{}'::jsonb)
        ) into v_req;
      end if;
      return jsonb_build_object('action','http_request','ok',true,
        'method', v_method, 'request_id', v_req);
    when 'update_related_item' then
      if nullif(p_action->>'field_id','') is null then
        return jsonb_build_object('action','update_related_item','ok',false,'reason','missing field_id');
      end if;
      v_cnt := 0;
      for v_rel in
        select distinct case when r.from_item_id = p_item then r.to_item_id else r.from_item_id end as rid
        from podio.item_relationships r
        where (r.from_item_id = p_item or r.to_item_id = p_item)
          and (nullif(p_action->>'relationship_field_id','') is null
               or r.field_id = (p_action->>'relationship_field_id')::uuid)
        limit 50
      loop
        insert into podio.item_field_values (item_id, field_id, position, value, value_text, value_number)
        values (v_rel.rid, (p_action->>'field_id')::uuid, 0, p_action->'value',
          case when jsonb_typeof(p_action->'value') = 'string' then p_action->'value' #>> '{}' end,
          case when jsonb_typeof(p_action->'value') = 'number' then (p_action->'value' #>> '{}')::numeric end)
        on conflict (item_id, field_id, position) do update
          set value = excluded.value, value_text = excluded.value_text,
              value_number = excluded.value_number, updated_at = now();
        v_cnt := v_cnt + 1;
      end loop;
      return jsonb_build_object('action','update_related_item','ok',true,'updated', v_cnt);
    when 'generate_pdf' then
      if p_actor is not null then
        insert into podio.comments (workspace_id, target_type, target_id, created_by, body)
        values (p_ws, 'item', p_item, p_actor,
          coalesce(nullif(p_action->>'note',''), '📄 PDF generated by ' || coalesce(p_auto_name, 'automation'))
          || ' — download: /api/pdf/' || p_item::text);
      end if;
      return jsonb_build_object('action','generate_pdf','ok',true,
        'url', '/api/pdf/' || p_item::text);
    else
      return jsonb_build_object('action', p_action->>'type', 'ok', false, 'reason', 'unknown action');
  end case;
  return jsonb_build_object('action', p_action->>'type', 'ok', true);
end $$;

-- ============================================================
-- 4) process_automation_run: approval (pause until task completes) + loop_related
-- ============================================================
create or replace function podio.process_automation_run(p_run uuid)
returns void
language plpgsql security definer set search_path = podio, public as $$
declare
  v_run podio.automation_runs;
  v_auto podio.automations;
  v_org uuid; v_ws uuid;
  v_actor uuid;
  v_queue jsonb;
  v_step jsonb;
  v_logs jsonb;
  v_task_id uuid;
  v_rel record;
  v_cnt int;
begin
  select * into v_run from podio.automation_runs where id = p_run and status = 'pending';
  if v_run.id is null then return; end if;
  select * into v_auto from podio.automations where id = v_run.automation_id;
  if v_auto.id is null then
    update podio.automation_runs set status = 'cancelled', finished_at = now() where id = p_run;
    return;
  end if;
  select a.workspace_id, w.organization_id into v_ws, v_org
  from podio.apps a join podio.workspaces w on w.id = a.workspace_id
  where a.id = v_auto.app_id;

  v_actor := coalesce(nullif(v_run.trigger_event->>'actor','')::uuid, v_auto.created_by);
  v_queue := coalesce(v_run.state->'queue', '[]'::jsonb);
  v_logs := coalesce(v_run.logs, '[]'::jsonb);

  update podio.automation_runs set status = 'running', started_at = coalesce(started_at, now())
  where id = p_run;

  begin
    while jsonb_array_length(v_queue) > 0 loop
      v_step := v_queue -> 0;
      v_queue := v_queue - 0;

      if v_step->>'type' = 'action' then
        v_logs := v_logs || jsonb_build_array(
          podio.exec_action(v_step->'config', v_org, v_ws, v_run.item_id, v_actor, v_auto.name));
      elsif v_step->>'type' = 'delay' then
        update podio.automation_runs
        set status = 'pending',
            scheduled_for = now() + (coalesce((v_step->>'hours')::numeric, 1) || ' hours')::interval,
            state = jsonb_build_object('queue', v_queue),
            logs = v_logs || jsonb_build_array(jsonb_build_object('action','delay','hours', v_step->>'hours','ok',true))
        where id = p_run;
        return;
      elsif v_step->>'type' = 'branch' then
        if podio.check_condition(v_run.item_id, v_step->'condition') then
          v_queue := coalesce(v_step->'then', '[]'::jsonb) || v_queue;
          v_logs := v_logs || jsonb_build_array(jsonb_build_object('action','branch','took','then'));
        else
          v_queue := coalesce(v_step->'else', '[]'::jsonb) || v_queue;
          v_logs := v_logs || jsonb_build_array(jsonb_build_object('action','branch','took','else'));
        end if;
      elsif v_step->>'type' = 'approval' then
        if v_actor is null then
          v_logs := v_logs || jsonb_build_array(jsonb_build_object(
            'action','approval','ok',false,'reason','no actor to create approval task'));
        else
          insert into podio.tasks
            (organization_id, workspace_id, target_type, target_id, title, assignee_id, created_by)
          values
            (v_org, v_ws, 'item', v_run.item_id,
             coalesce(nullif(v_step->>'title',''), 'Approval required: ' || v_auto.name),
             nullif(v_step->>'assignee_id','')::uuid, v_actor)
          returning id into v_task_id;

          if nullif(v_step->>'assignee_id','') is not null then
            insert into podio.notifications (user_id, event_type, target_type, target_id, actor_id, payload)
            values ((v_step->>'assignee_id')::uuid, 'task_assigned', 'item', v_run.item_id, v_actor,
              jsonb_build_object('task_title', coalesce(nullif(v_step->>'title',''), 'Approval required'),
                'automation', v_auto.name, 'approval', true));
          end if;

          update podio.automation_runs
          set status = 'pending',
              scheduled_for = 'infinity',
              state = jsonb_build_object('queue', v_queue, 'waiting_task', v_task_id),
              logs = v_logs || jsonb_build_array(jsonb_build_object(
                'action','approval','ok',true,'waiting',true,'task_id', v_task_id))
          where id = p_run;
          return;
        end if;
      elsif v_step->>'type' = 'loop_related' then
        v_cnt := 0;
        for v_rel in
          select distinct case when r.from_item_id = v_run.item_id then r.to_item_id else r.from_item_id end as rid
          from podio.item_relationships r
          where (r.from_item_id = v_run.item_id or r.to_item_id = v_run.item_id)
            and (nullif(v_step->>'relationship_field_id','') is null
                 or r.field_id = (v_step->>'relationship_field_id')::uuid)
          limit 50
        loop
          perform podio.exec_action(v_step->'action', v_org, v_ws, v_rel.rid, v_actor, v_auto.name);
          v_cnt := v_cnt + 1;
        end loop;
        v_logs := v_logs || jsonb_build_array(jsonb_build_object(
          'action','loop_related','ok',true,'iterations', v_cnt));
      end if;
    end loop;

    update podio.automation_runs
    set status = 'success', logs = v_logs, state = '{}'::jsonb, finished_at = now()
    where id = p_run;
  exception when others then
    update podio.automation_runs
    set status = 'failed', error = SQLERRM, logs = v_logs, finished_at = now()
    where id = p_run;
  end;
end $$;

-- Resume approval-gated runs when their task is completed
create or replace function podio.trg_task_completed_automations()
returns trigger
language plpgsql security definer set search_path = podio, public as $$
begin
  if pg_trigger_depth() > 1 then return new; end if;
  if new.completed_at is not null and old.completed_at is null then
    -- resume any flow waiting on this task as an approval gate
    update podio.automation_runs r
    set scheduled_for = now(),
        state = r.state - 'waiting_task',
        logs = coalesce(r.logs, '[]'::jsonb) || jsonb_build_array(jsonb_build_object(
          'action','approval','ok',true,'approved_by', new.completed_by))
    where r.status = 'pending' and r.state->>'waiting_task' = new.id::text;

    if new.target_type = 'item' and new.target_id is not null then
      perform podio.run_simple_automations(
        i.app_id, new.target_id, 'task_completed', coalesce(new.completed_by, new.assignee_id))
      from podio.items i
      where i.id = new.target_id and not i.is_deleted;
    end if;
  end if;
  return new;
end $$;

-- ============================================================
-- 5) Flow versioning: snapshot to automation_revisions on every change
-- ============================================================
create or replace function podio.tg_automation_revision()
returns trigger
language plpgsql security definer set search_path = podio, public as $$
begin
  if (old.name, old.trigger, old.conditions, old.actions, old.definition)
     is distinct from
     (new.name, new.trigger, new.conditions, new.actions, new.definition) then
    insert into podio.automation_revisions (automation_id, version, snapshot, created_by)
    values (old.id, old.version, jsonb_build_object(
      'name', old.name, 'kind', old.kind, 'trigger', old.trigger,
      'conditions', old.conditions, 'actions', old.actions, 'definition', old.definition),
      auth.uid())
    on conflict (automation_id, version) do nothing;
    new.version := old.version + 1;
  end if;
  return new;
end $$;

drop trigger if exists trg_automations_revision on podio.automations;
create trigger trg_automations_revision
before update on podio.automations
for each row execute function podio.tg_automation_revision();

create or replace function podio.restore_automation_revision(p_revision uuid)
returns void
language plpgsql security definer set search_path = podio, public as $$
declare
  v_rev podio.automation_revisions;
  v_auto podio.automations;
begin
  select * into v_rev from podio.automation_revisions where id = p_revision;
  if v_rev.id is null then raise exception 'revision not found'; end if;
  select * into v_auto from podio.automations where id = v_rev.automation_id;
  if v_auto.id is null or not podio.is_workspace_member(v_auto.workspace_id) then
    raise exception 'no access to automation';
  end if;

  update podio.automations
  set name = coalesce(v_rev.snapshot->>'name', name),
      trigger = coalesce(v_rev.snapshot->'trigger', trigger),
      conditions = coalesce(v_rev.snapshot->'conditions', conditions),
      actions = coalesce(v_rev.snapshot->'actions', actions),
      definition = v_rev.snapshot->'definition',
      updated_by = auth.uid()
  where id = v_auto.id;
end $$;
grant execute on function podio.restore_automation_revision(uuid) to authenticated;

-- ============================================================
-- 6) get_webform: expose captcha flag (verification handled by /api/forms/submit)
-- ============================================================
create or replace function podio.get_webform(p_slug text)
returns jsonb
language sql stable security definer set search_path = podio, public as $$
  select jsonb_build_object(
    'slug', f.slug,
    'title', f.title,
    'description', f.description,
    'success_message', coalesce(f.settings->>'success_message', 'Thank you! Your submission was received.'),
    'redirect_url', f.settings->>'redirect_url',
    'theme', coalesce(f.settings->'theme', '{}'::jsonb),
    'custom_css', f.settings->>'custom_css',
    'captcha_enabled', coalesce((f.settings->>'captcha_enabled')::boolean, false),
    'app_name', a.name,
    'icon', a.icon,
    'item_name', a.item_name,
    'fields', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', af.id, 'external_id', af.external_id, 'label', af.label, 'type', af.type,
        'is_required', af.is_required, 'help_text', af.help_text, 'config', af.config
      ) order by af.position), '[]'::jsonb)
      from podio.app_fields af
      where af.app_id = a.id and af.status = 'active'
        and af.id = any(f.field_ids)
        and af.type not in ('relationship','contact','image','file','calculation')
    )
  )
  from podio.webforms f
  join podio.apps a on a.id = f.app_id
  where f.slug = p_slug and f.is_active;
$$;

-- ============================================================
-- 7) Org backup export (org admins): full JSON snapshot
-- ============================================================
create or replace function podio.export_org_backup(p_org uuid)
returns jsonb
language plpgsql security definer set search_path = podio, public as $$
declare
  v_result jsonb;
begin
  if not podio.is_org_admin(p_org) then
    raise exception 'only org admins can export a backup';
  end if;

  select jsonb_build_object(
    'exported_at', now(),
    'format_version', 1,
    'organization', (select jsonb_build_object('id', o.id, 'name', o.name, 'slug', o.slug,
        'created_at', o.created_at) from podio.organizations o where o.id = p_org),
    'workspaces', (select coalesce(jsonb_agg(jsonb_build_object(
        'id', w.id, 'name', w.name, 'slug', w.slug, 'privacy', w.privacy,
        'is_archived', w.is_archived, 'created_at', w.created_at)), '[]'::jsonb)
      from podio.workspaces w where w.organization_id = p_org),
    'apps', (select coalesce(jsonb_agg(jsonb_build_object(
        'id', a.id, 'workspace_id', a.workspace_id, 'name', a.name, 'slug', a.slug,
        'icon', a.icon, 'item_name', a.item_name, 'description', a.description,
        'is_archived', a.is_archived,
        'fields', (select coalesce(jsonb_agg(jsonb_build_object(
            'id', f.id, 'external_id', f.external_id, 'label', f.label, 'type', f.type,
            'config', f.config, 'is_required', f.is_required, 'is_primary', f.is_primary,
            'position', f.position, 'status', f.status) order by f.position), '[]'::jsonb)
          from podio.app_fields f where f.app_id = a.id)
        )), '[]'::jsonb)
      from podio.apps a
      join podio.workspaces w on w.id = a.workspace_id
      where w.organization_id = p_org),
    'items', (select coalesce(jsonb_agg(x.item), '[]'::jsonb) from (
        select jsonb_build_object(
          'id', i.id, 'app_id', i.app_id, 'item_number', i.item_number, 'title', i.title,
          'created_at', i.created_at, 'updated_at', i.updated_at,
          'values', (select coalesce(jsonb_object_agg(af.external_id, ifv.value), '{}'::jsonb)
            from podio.item_field_values ifv
            join podio.app_fields af on af.id = ifv.field_id
            where ifv.item_id = i.id)) as item
        from podio.items i
        join podio.apps a on a.id = i.app_id
        join podio.workspaces w on w.id = a.workspace_id
        where w.organization_id = p_org and not i.is_deleted
        order by i.created_at
        limit 10000
      ) x),
    'tasks', (select coalesce(jsonb_agg(jsonb_build_object(
        'id', t.id, 'title', t.title, 'description', t.description, 'status', t.status,
        'due_at', t.due_at, 'completed_at', t.completed_at, 'target_type', t.target_type,
        'target_id', t.target_id, 'created_at', t.created_at)), '[]'::jsonb)
      from podio.tasks t where t.organization_id = p_org),
    'automations', (select coalesce(jsonb_agg(jsonb_build_object(
        'id', au.id, 'app_id', au.app_id, 'name', au.name, 'kind', au.kind,
        'status', au.status, 'version', au.version, 'trigger', au.trigger,
        'conditions', au.conditions, 'actions', au.actions, 'definition', au.definition)), '[]'::jsonb)
      from podio.automations au
      join podio.workspaces w on w.id = au.workspace_id
      where w.organization_id = p_org),
    'webforms', (select coalesce(jsonb_agg(jsonb_build_object(
        'id', wf.id, 'app_id', wf.app_id, 'slug', wf.slug, 'title', wf.title,
        'field_ids', wf.field_ids, 'settings', wf.settings, 'is_active', wf.is_active)), '[]'::jsonb)
      from podio.webforms wf
      join podio.apps a on a.id = wf.app_id
      join podio.workspaces w on w.id = a.workspace_id
      where w.organization_id = p_org)
  ) into v_result;

  insert into podio.audit_logs (organization_id, actor_id, action, target_type, metadata)
  values (p_org, auth.uid(), 'org.backup_exported', 'organization',
    jsonb_build_object('item_count', jsonb_array_length(v_result->'items')));

  return v_result;
end $$;
grant execute on function podio.export_org_backup(uuid) to authenticated;
